# Generated by Django 5.2.7 on 2025-11-07 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'role': 'TEACHER'}, related_name='course_taught', to=settings.AUTH_USER_MODEL),
        ),
    ]
